#!/bin/sh

set -o nounset
set -e

{{~#eachAlive bind.database.members as |member|}}
    echo "Bound to database {{member.sys.ip}} on {{member.cfg.port}}"
{{else}}
    echo "No bound databases"
{{~/eachAlive}}

export LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
export HOME={{pkg.svc_var_path}}
export RELEASE_MUTABLE_DIR={{pkg.svc_var_path}}
export ERTS_VSN="8.1"
#export PATH={{pkgPathFor "core/erlang"}}/bin:$PATH

exec 2>&1

exec aptamer command bootstrap
exec aptamer command migrate

