#!/bin/sh

exec 2>&1

export LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
export HOME={{pkg.svc_var_path}}
export RELEASE_MUTABLE_DIR={{pkg.svc_var_path}}

export APTAMER_PYTHON="$(hab pkg path chrisortman/aptamer-scripts)/bin/run-aptamer"
export APTAMER_SCRIPT="$(hab pkg path chrisortman/aptamer-scripts)/scripts"
export SMTP_PASSWORD="{{cfg.smtp_password}}"

exec aptamer foreground
