language: elixir
elixir: 1.5.1
otp_release: '20.0'
sudo: required
addons:
  postgresql: '9.6'
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
branches:
  except:
    - "/^v?\\d+\\.\\d+\\.\\d+$/"
before_install:
  - openssl aes-256-cbc -K $encrypted_9f4aecea9b7f_key -iv $encrypted_9f4aecea9b7f_iv -in chrisortman-20160618040827.sig.key.enc -out chrisortman-20160618040827.sig.key -d
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
install:
  - cd backend/
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - cd ../frontend
  - mkdir travis-phantomjs
  - wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2
  - tar -xvf $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -C $PWD/travis-phantomjs
  - export PATH=$PWD/travis-phantomjs:$PATH
  - yarn global add bower
  - yarn install
  - npm install -g ember-cli
  - bower install
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - cd ../backend
  - cp config/travis.exs config/test.exs
  - mix do ecto.create, ecto.migrate
script:
  - mix test
  - cd ../frontend
  - ember test
before_deploy:
  - cd ..
  - 'semver=$({ sed -nE ''s/^[ \t]*"version": "([0-9]{1,}\.[0-9]{1,}\.)[0-9x]{1,}",$/\1/p''
    version.txt; git describe --abbrev=0 | sed -E ''s/^v([0-9]{1,}\.[0-9]{1,}\.)([0-9]{1,})$/\1
    \2/g''; } | tr "\n" " " | awk ''{printf($1==$2?"v"$2$3+1:"v"$1"0")}'') '
  - echo $semver
deploy:
  provider: script
  script: deploy-with-habitat.sh
  skip_cleanup: true
  on:
    repo: ui-icts/aptamer-web
    branch: master
env:
  global:
    secure: URJJ27QxU9rBZs9xPb5MCtuDMXiKw4B6Y4DP0sPq2W4hMQV0uVPh7lVVDQk4D4GX6rlUwtbC+oYNaq2keDB3D117MToDLEoJe5yuPSOLyXK9ZmZCFxLH8b76VGUGpqiwRGT6uxx1Gox5dcb3PwkhMWvpZj+NKaYoCIpLL9sU/aGgn6xfccSvErlDCV+neXKYzQT1xB6rX7Jjx+Ml4G9/LrukiEB8GDVay2e+xkGXHyduJ0PAEohWOBf/IIPHgHR0MkZ8fDUBgjR/bmyddD9j1d99tga90Zei/pAIRrl+SvhPe4q8Ch8+qakicbGwS5q6sYrfnN5MTgySlur3whuhNmObsETeYF6KKvC6WTeSSClAjbxBjlHzegFaNhhhpThSF5+DVCphNNSAErKBkeJnG+udgk9brrM/yDYMRT4lFA1TfFc5267BaMkF8Z4NsM/Lo/9MED/NVqE2Nyh6JKjHHCSYW72RI3VDJ+ywCbf6KON0/Eslay0pNxXM98v5PxXqq+lU93oel0b/T+Pbpfu+6+xV2JqGXbHJ4651J/W8Tkv0uzhNmyt/6xLAMs2eEon/6LHVqfz/XCtVLS2W83yYv1l0F8182vOak58FWMsZ0zGyaCCMwHDis3ih7fPvNmVUuA3H7TYhQujmbknLijMpi2m5+o1p7L8EQOTu9Y2F41o=
