language: elixir

elixir:
  - 1.5.1

otp_release: '18.0'

addons:
  postgresql: '9.6.4'

services:
  - postgresql

before_script:
  - cd backend
  - cp config/travis.exs config/test.exs
  - mix do ecto.create, ecto.migrate

script:
  - mix test
