language: elixir
elixir: 1.8
otp_release: '20.0'
sudo: required
env:
  matrix:
    - TRAVIS_NODE_VERSION="8.12.0"
  global:
  - PGPORT=5433
  - secure: qOj52EvuYxs00aqpCtoWWQX4HuViv+LylxpbXzjxL1RzsAA183CLGOY9xiSwlDM6LoctaAzBdOq2UqmuzBmzQZE5Cd/Wgw1pgF+3P9/eaxvmQhwy3RmzDrjFUo8RC9KXKutjTdNyA+bI21OxgkrujF4BtMGttp+lnHqpKm2NnHqEYIA4BtpSsXV/0k1kVxrDMQsev8bvLEDfR66Mk2XUKJf3oKeNFX0/oGqdkUr2utyrI4WlQcEk8VHVgnfh+cUl2i9RtImVzAxwtOgU1MyvoCQnUNu5m/Sis46mi7kcLW622Xg/Q1+x+8VWuq7kXTL9RiIjb/tsrpDHKm+/lyesYON0kvkA4HE2JD2YXGH0LAKP3mWNIEY7AeDkEDXA30EnLfaOoXc740PZvZZILAbLSTzMk7DLbeVhbspBOioNOQqQPnlwrhj/AMm1uHZweWCvXjSwO/z9Gg5ieFxBUOWNYFe0/UbUtVKc4ktcT5zsGkCI2Ahsj1dorTrz1KWcuo8Q9g3rZOHCyhExFsoSXtn0gK9L9JDMAmqo4Sd/JCUBm2Dnk8HE/8rat6FuXyLJde/lAAWczB93+34HoTsUMFrKaWoaXseS33lv02wYHjp++xufJouZQ5N+uJunS1iOhE5WYelI+nLWPzlQ9+C850jFXgsLpraPA0XqZ6O/v2DVK5M=
addons:
  postgresql: '10'
  apt:
    sources:
      - google-chrome
    packages:
      - postgresql-10
      - postgresql-client-10
      - google-chrome-stable
branches:
  except:
    - "/^v?\\d+\\.\\d+\\.\\d+$/"
before_install:
  - openssl aes-256-cbc -K $encrypted_9f4aecea9b7f_key -iv $encrypted_9f4aecea9b7f_iv -in chrisortman-20160618040827.sig.key.enc -out chrisortman-20160618040827.sig.key -d
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
install:
  - cd backend/
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - cd ../frontend
  - mkdir travis-phantomjs
  - wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2
  - tar -xvf $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -C $PWD/travis-phantomjs
  - export PATH=$PWD/travis-phantomjs:$PATH
  - nvm install $TRAVIS_NODE_VERSION
  - nvm use $TRAVIS_NODE_VERSION
  - yarn install --non-interactive
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - cd ../backend
  - cp config/travis.exs config/test.exs
  - mix do ecto.create, ecto.migrate
script:
  - mix test
  - cd ../frontend
  - yarn lint:js
  - yarn test
before_deploy:
  - cd ..
  - 'semver=$({ sed -nE ''s/^[ \t]*"version": "([0-9]{1,}\.[0-9]{1,}\.)[0-9x]{1,}",$/\1/p''
    version.txt; git describe --abbrev=0 | sed -E ''s/^v([0-9]{1,}\.[0-9]{1,}\.)([0-9]{1,})$/\1
    \2/g''; } | tr "\n" " " | awk ''{printf($1==$2?"v"$2$3+1:"v"$1"0")}'') '
  - echo $semver
  - echo $PWD
  - ls -al
deploy:
  provider: script
  script: ./deploy-with-habitat.sh
  skip_cleanup: true
  on:
    repo: ui-icts/aptamer-web
    branch: master
