FROM registry.git.uiowa.edu:5005/ccom/research/aptamer-scripts:latest as scripts

WORKDIR /app
COPY --from=aptamer-web:latest /app .

ENV MIX_ENV=prod \
    SHELL=/bin/bash
ENTRYPOINT ["/app/bin/aptamer"]
CMD ["eval", "Aptamer.ReleaseTasks.process_jobs"]
